// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACOAFsYLaq8ipaxEARsTPelqq1UVoWNBA',
    appId: '1:98910437031:web:4152afb3ed107adadaa582',
    messagingSenderId: '98910437031',
    projectId: 'we-chat-da500',
    authDomain: 'we-chat-da500.firebaseapp.com',
    storageBucket: 'we-chat-da500.firebasestorage.app',
    measurementId: 'G-EB9TL314J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl347qGPs8x5IwgNqBD_IscoK16OzeWNk',
    appId: '1:98910437031:android:18c5095234319ecddaa582',
    messagingSenderId: '98910437031',
    projectId: 'we-chat-da500',
    storageBucket: 'we-chat-da500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBarapJDv_pXs9Wi5oWsA4mDJLP8T2Zns0',
    appId: '1:98910437031:ios:27e64133cb1ef9f6daa582',
    messagingSenderId: '98910437031',
    projectId: 'we-chat-da500',
    storageBucket: 'we-chat-da500.firebasestorage.app',
    androidClientId: '98910437031-vpsf2kk8vapvo6agsfvcsdib3omo20ha.apps.googleusercontent.com',
    iosClientId: '98910437031-lhejpj8uldnhtgi8tnkkk5jtfk6bifkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

}